Repository Booklay/booklay-shop, pull requests merged in 2023-01, with the labels that each got.

#3 Feature/entity mapping
  .github/workflows/ci.yml
  pom.xml
  src/main/java/com/nhnacademy/booklay/server/entity/AskChat.java
  src/main/java/com/nhnacademy/booklay/server/entity/Author.java
  src/main/java/com/nhnacademy/booklay/server/entity/Authority.java
  src/main/java/com/nhnacademy/booklay/server/entity/BlockedMemberDetail.java
  src/main/java/com/nhnacademy/booklay/server/entity/Category.java
  src/main/java/com/nhnacademy/booklay/server/entity/CouponType.java
  src/main/java/com/nhnacademy/booklay/server/entity/DeliveryDestination.java
  src/main/java/com/nhnacademy/booklay/server/entity/Gender.java
  src/main/java/com/nhnacademy/booklay/server/entity/Image.java
  src/main/java/com/nhnacademy/booklay/server/entity/Member.java
  src/main/java/com/nhnacademy/booklay/server/entity/MemberAuthority.java
  src/main/java/com/nhnacademy/booklay/server/entity/MemberGrade.java
  src/main/java/com/nhnacademy/booklay/server/entity/Order.java
  src/main/java/com/nhnacademy/booklay/server/entity/OrderStatusCode.java
  src/main/java/com/nhnacademy/booklay/server/entity/PointHistory.java
  src/main/java/com/nhnacademy/booklay/server/entity/PostType.java
  src/main/java/com/nhnacademy/booklay/server/entity/Product.java
  src/main/java/com/nhnacademy/booklay/server/entity/ProductAuthor.java
  src/main/java/com/nhnacademy/booklay/server/entity/ProductDetail.java
  src/main/java/com/nhnacademy/booklay/server/entity/Tag.java
  src/main/java/com/nhnacademy/booklay/server/repository/GenderRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/MemberRepository.java
  src/main/resources/application.yml
  src/main/resources/templates/dummy.html
  src/main/resources/templates/web/admin/main.html
  src/main/resources/templates/web/admin/product/main.html
  src/main/resources/templates/web/index.html
  src/test/java/com/nhnacademy/booklay/server/BooklayShopApplicationTests.java
  src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/booklay/server/repository/MemberRepositoryTest.java
  src/test/resources/application-test.yml
  src/test/resources/data.sql
Labels: enhancement

#6 Feature/entity mixed repository
  src/main/java/com/nhnacademy/booklay/server/entity/Coupon.java
  src/main/java/com/nhnacademy/booklay/server/entity/OrderProduct.java
  src/main/java/com/nhnacademy/booklay/server/entity/ViewCount.java
  src/main/java/com/nhnacademy/booklay/server/entity/Wishlist.java
  src/main/java/com/nhnacademy/booklay/server/repository/CouponRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/OrderProductRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/ViewCountRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/WishlistRepository.java
  src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/booklay/server/repository/CouponRepositoryTest.java
Labels: enhancement

#16 fix: add jacoco dependency and fix member test failure
  pom.xml
  src/test/java/com/nhnacademy/booklay/server/repository/MemberRepositoryTest.java
Labels: feature

#19 feat: coupon crud 작성 #124
  src/main/java/com/nhnacademy/booklay/server/controller/admin/CouponAdminController.java
  src/main/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminService.java
Labels: feature

#22 feat:member read 기능 추가 #23
  src/main/java/com/nhnacademy/booklay/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/MemberDto.java
  src/main/java/com/nhnacademy/booklay/server/repository/MemberRepository.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
Labels: feature

#31 멤버 브랜치 리펙토링
  pom.xml
  src/main/java/com/nhnacademy/booklay/server/controller/WebControllerAdvice.java
  src/main/java/com/nhnacademy/booklay/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/booklay/server/dto/ErrorResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/request/MemberCreateRequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/request/MemberUpdateRequest.java
  src/main/java/com/nhnacademy/booklay/server/entity/Member.java
  src/main/java/com/nhnacademy/booklay/server/exception/ApiException.java
  src/main/java/com/nhnacademy/booklay/server/exception/CommonErrorCode.java
  src/main/java/com/nhnacademy/booklay/server/exception/ErrorCode.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
  src/test/java/com/nhnacademy/booklay/server/controller/member/MemberControllerTest.java
  src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
Labels: refactor

#42 Feature/member authority
  src/main/java/com/nhnacademy/booklay/server/controller/member/MemberAdminController.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/entity/Member.java
  src/main/java/com/nhnacademy/booklay/server/repository/AuthorityRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/CartRepository.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
  src/test/java/com/nhnacademy/booklay/server/controller/member/MemberAdminControllerTest.java
  src/test/java/com/nhnacademy/booklay/server/controller/member/MemberControllerTest.java
  src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/booklay/server/repository/AuthorityRepositoryTest.java
  src/test/java/com/nhnacademy/booklay/server/service/member/MemberServiceImplTest.java
Labels: feature

#40 RestTemplate 요청에 응답할 수 있도록 일부 코드 수정
  src/main/java/com/nhnacademy/booklay/server/controller/admin/CategoryAdminController.java
  src/main/java/com/nhnacademy/booklay/server/dto/PageResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/category/request/CategoryCreateRequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/category/response/CategoryResponse.java
  src/main/java/com/nhnacademy/booklay/server/entity/Category.java
  src/main/java/com/nhnacademy/booklay/server/service/category/CategoryService.java
  src/main/java/com/nhnacademy/booklay/server/service/category/CategoryServiceImpl.java
  src/test/java/com/nhnacademy/booklay/server/controller/admin/CategoryAdminControllerTest.java
Labels: feature

#45 Feature/member grade/authority
  src/main/java/com/nhnacademy/booklay/server/controller/member/MemberAdminController.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberGradeRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/MemberGradeRepository.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
  src/test/java/com/nhnacademy/booklay/server/controller/member/MemberAdminControllerTest.java
  src/test/java/com/nhnacademy/booklay/server/controller/member/MemberControllerTest.java
  src/test/java/com/nhnacademy/booklay/server/service/member/MemberServiceImplTest.java
Labels: feature

#47 fix: memberId 중복체크 기능 구현
  src/main/java/com/nhnacademy/booklay/server/entity/Authority.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
  src/test/java/com/nhnacademy/booklay/server/controller/member/MemberAdminControllerTest.java
  src/test/java/com/nhnacademy/booklay/server/service/member/MemberServiceImplTest.java
Labels: feature

#49 오브젝트 스토리지 적용
  src/main/java/com/nhnacademy/booklay/server/controller/storage/StorageController.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/request/FileRequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/request/FileResolveRequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/request/auth/AccessRequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/request/auth/Auth.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/request/auth/PasswordCredentials.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/response/ObjectFileResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/response/auth/Access.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/response/auth/AccessResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/response/auth/Tenant.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/response/auth/Token.java
  src/main/java/com/nhnacademy/booklay/server/dto/stroage/response/auth/User.java
  src/main/java/com/nhnacademy/booklay/server/entity/ObjectFile.java
  src/main/java/com/nhnacademy/booklay/server/exception/ImageNotFoundException.java
  src/main/java/com/nhnacademy/booklay/server/repository/ObjectFileRepository.java
  src/main/java/com/nhnacademy/booklay/server/service/storage/FileService.java
  src/main/java/com/nhnacademy/booklay/server/service/storage/StorageService.java
  src/main/java/com/nhnacademy/booklay/server/service/storage/impl/CloudStorageService.java
  src/main/java/com/nhnacademy/booklay/server/service/storage/impl/FileServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/nhnacademy/booklay/server/controller/admin/CategoryAdminControllerTest.java
  src/test/resources/application-test.yml
  src/test/resources/data.sql
Labels: feature

#55 feat: logback.xml 적용
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-prod.xml
Labels: feature

#57 Feature/member address ud
  src/main/java/com/nhnacademy/booklay/server/controller/delivery/DeliveryDestinationController.java
  src/main/java/com/nhnacademy/booklay/server/dto/delivery/request/DeliveryDestinationCURequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/delivery/response/DeliveryDestinationRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/service/member/DeliveryDestinationService.java
  src/main/java/com/nhnacademy/booklay/server/service/member/DeliveryDestinationServiceImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
  src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/booklay/server/repository/delivery/DeliveryDestinationRepositoryTest.java
  src/test/java/com/nhnacademy/booklay/server/service/delivery/DeliveryDestinationServiceImplTest.java
Labels: feature

#59 Feature/member address cu
  src/main/java/com/nhnacademy/booklay/server/controller/delivery/DeliveryDestinationController.java
  src/main/java/com/nhnacademy/booklay/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/booklay/server/controller/mypage/PointHistoryController.java
  src/main/java/com/nhnacademy/booklay/server/dto/delivery/request/DeliveryDestinationCURequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/delivery/response/DeliveryDestinationRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/PointHistoryRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/TotalPointRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/request/PointHistoryCreateRequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/request/PointPresentRequest.java
  src/main/java/com/nhnacademy/booklay/server/entity/DeliveryDestination.java
  src/main/java/com/nhnacademy/booklay/server/entity/MemberAuthority.java
  src/main/java/com/nhnacademy/booklay/server/exception/delivery/DeliveryDestinationLimitExceededException.java
  src/main/java/com/nhnacademy/booklay/server/exception/delivery/DeliveryDestinationNotFoundException.java
  src/main/java/com/nhnacademy/booklay/server/exception/member/AdminAndAuthorAuthorityCannotExistTogetherException.java
  src/main/java/com/nhnacademy/booklay/server/exception/member/AlreadyExistAuthorityException.java
  src/main/java/com/nhnacademy/booklay/server/exception/member/AuthorityNotFoundException.java
  src/main/java/com/nhnacademy/booklay/server/exception/member/MemberAuthorityCannotBeDeletedException.java
  src/main/java/com/nhnacademy/booklay/server/exception/member/MemberAuthorityNotFoundException.java
  src/main/java/com/nhnacademy/booklay/server/exception/member/MemberNotFoundException.java
  src/main/java/com/nhnacademy/booklay/server/repository/delivery/DeliveryDestinationRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/delivery/DeliveryDestinationRepositoryCustom.java
  src/main/java/com/nhnacademy/booklay/server/repository/delivery/DeliveryDestinationRepositoryImpl.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryCustom.java
  src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/delivery/DeliveryDestinationService.java
  src/main/java/com/nhnacademy/booklay/server/service/delivery/DeliveryDestinationServiceImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/member/DeliveryDestinationServiceImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/member/GetMemberService.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryService.java
  src/main/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryServiceImpl.java
  src/main/resources/application-dev.yml
  src/test/java/com/nhnacademy/booklay/server/controller/member/MemberControllerTest.java
  src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/booklay/server/repository/delivery/DeliveryDestinationRepositoryTest.java
  src/test/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryTest.java
  src/test/java/com/nhnacademy/booklay/server/service/delivery/DeliveryDestinationServiceImplTest.java
  src/test/java/com/nhnacademy/booklay/server/service/member/MemberServiceImplTest.java
  src/test/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryServiceImplTest.java
Labels: feature

#62 feat: 포인트 조회 구현, 포인트 선물하기 보완
  src/main/java/com/nhnacademy/booklay/server/controller/mypage/PointHistoryController.java
  src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryCustom.java
  src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryService.java
  src/main/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryServiceImpl.java
  src/test/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryTest.java
Labels: feature

#66 Feature/member point coupon
  src/main/java/com/nhnacademy/booklay/server/controller/member/MemberController.java
  src/main/java/com/nhnacademy/booklay/server/controller/mypage/PointHistoryController.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/MemberRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryCustom.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryImpl.java
  src/main/java/com/nhnacademy/booklay/server/repository/mypage/PointHistoryRepositoryImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/delivery/DeliveryDestinationServiceImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/mypage/PointHistoryServiceImpl.java
  src/test/java/com/nhnacademy/booklay/server/repository/MemberRepositoryTest.java
  src/test/java/com/nhnacademy/booklay/server/service/member/MemberServiceImplTest.java
Labels: feature

#68 Feature/member block
  src/main/java/com/nhnacademy/booklay/server/BooklayShopApplication.java
  src/main/java/com/nhnacademy/booklay/server/controller/admin/member/MemberAdminController.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/reponse/BlockedMemberRetrieveResponse.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/request/MemberAuthorityUpdateRequest.java
  src/main/java/com/nhnacademy/booklay/server/dto/member/request/MemberBlockRequest.java
  src/main/java/com/nhnacademy/booklay/server/entity/Member.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/BlockedMemberDetailRepository.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/BlockedMemberDetailRepositoryCustom.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/BlockedMemberDetailRepositoryImpl.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryCustom.java
  src/main/java/com/nhnacademy/booklay/server/repository/member/MemberRepositoryImpl.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberService.java
  src/main/java/com/nhnacademy/booklay/server/service/member/MemberServiceImpl.java
  src/main/resources/META-INF/MANIFEST.MF
  src/test/java/com/nhnacademy/booklay/server/dummy/Dummy.java
  src/test/java/com/nhnacademy/booklay/server/repository/BlockedMemberDetailRepositoryTest.java
  src/test/java/com/nhnacademy/booklay/server/repository/MemberRepositoryTest.java
  src/test/java/com/nhnacademy/booklay/server/repository/product/AuthorRepositoryTest.java
  src/test/java/com/nhnacademy/booklay/server/service/coupon/CouponAdminServiceImplTest.java
  src/test/resources/application-test.yml
Labels: feature

#72 fix: StorageController
  src/main/java/com/nhnacademy/booklay/server/controller/storage/StorageController.java
  src/main/resources/application-prod.yml
Labels: feature, refactor
